#!/usr/bin/env bash
# GENERATED by scripts/build-adapters.mjs from skills/. Do not edit by hand.
# Kiro Crew runs this once at install (setup.onInstall). The 18 skills are
# vendored under skills/, so this only verifies them and prints the MCP step.
set -euo pipefail
APP_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
count="$(find "${APP_ROOT}/skills" -maxdepth 2 -name SKILL.md 2>/dev/null | wc -l | tr -d ' ')"
echo "[katalon-testing-skills] ${count} skills present under skills/"
if [ "${count}" -lt 1 ]; then echo "[katalon-testing-skills] no skills found" >&2; exit 1; fi
echo "[katalon-testing-skills] Next: the katalon-prod-mcp server is declared in app.json."
echo "[katalon-testing-skills] First connect opens a browser OAuth flow at https://platform.katalon.io/mcp and lets you pick your workspace."
